name: '${name}'
version: '${version}'
main: '${main}'
api-version: '${api}'
description: '${description}'
website: '${website}'
softdepend:
  - ItemsAdder
  - Oraxen
  - HeadsDatabase
depend:
  - PlaceholderAPI
libraries:
  - net.kyori:adventure-api:${adventureVersion}
  - net.kyori:adventure-platform-bukkit:${adventureBukkitVersion}
  - net.kyori:adventure-text-minimessage:${adventureVersion}
  - org.spongepowered:configurate-hocon:${configurateVersion}