name: ConfigurableMenus
version: '${project.version}'
main: com.lapzupi.dev.configurablemenus.ConfigurableMenusPlugin
api-version: 1.18
description: ${project.description}
website: ${project.url}
softdepend:
  - ItemsAdder
  - Oraxen
  - HeadsDatabase
depend:
  - PlaceholderAPI
libraries:
  - net.kyori:adventure-api:${adventure.version}
  - net.kyori:adventure-platform-bukkit:${adventure.bukkit.version}
  - net.kyori:adventure-text-minimessage:${adventure.version}
  - org.spongepowered:configurate-hocon:${configurate.version}